# Once a day sidekiq-cron is triggered to perform this work DestroyOldNotificationsWorker
# cron value can be changed to run more than once a day
destroy_old_notifications:
   cron: "0 0 * * *"
   class: "DestroyOldNotificationsWorker"
